// ISO alpha-2 -> country name, for the codes that actually appear in
// backend/data/seed/zones.yaml (zone_1/zone_2/zone_3) plus the two
// hardcoded-excluded codes (EG, SA). Zone 3 is "and the rest," so a
// country outside this list can still appear -- countryLabel() falls back
// to the raw code rather than requiring exhaustive ISO coverage.
const COUNTRY_NAMES = {
  AU: "Australia",
  AT: "Austria",
  BE: "Belgium",
  CA: "Canada",
  DK: "Denmark",
  FI: "Finland",
  FR: "France",
  DE: "Germany",
  GR: "Greece",
  IS: "Iceland",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JP: "Japan",
  KR: "Korea",
  LI: "Liechtenstein",
  LU: "Luxembourg",
  NL: "Netherlands",
  NZ: "New Zealand",
  NO: "Norway",
  PT: "Portugal",
  SG: "Singapore",
  ES: "Spain",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  GB: "United Kingdom",
  US: "United States",
  HU: "Hungary",
  PL: "Poland",
  BG: "Bulgaria",
  RU: "Russia",
  HR: "Croatia",
  SK: "Slovakia",
  CY: "Cyprus",
  SI: "Slovenia",
  CZ: "Czech Republic",
  LV: "Latvia",
  LT: "Lithuania",
  EE: "Estonia",
  MT: "Malta",

  AR: "Argentina",
  BH: "Bahrain",
  BY: "Belarus",
  BO: "Bolivia",
  BR: "Brazil",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CU: "Cuba",
  EC: "Ecuador",
  EG: "Egypt",
  GF: "French Guiana",
  GY: "Guyana",
  MK: "North Macedonia",
  MX: "Mexico",
  MD: "Moldova",
  MA: "Morocco",
  OM: "Oman",
  PY: "Paraguay",
  PE: "Peru",
  QA: "Qatar",
  SA: "Saudi Arabia",
  RS: "Serbia",
  ZA: "South Africa",
  SR: "Suriname",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  UY: "Uruguay",
  VE: "Venezuela",
  HK: "Hong Kong",
  MO: "Macau",

  DZ: "Algeria",
  BD: "Bangladesh",
  CM: "Cameroon",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  JO: "Jordan",
  KW: "Kuwait",
  MY: "Malaysia",
  NG: "Nigeria",
  PK: "Pakistan",
  PH: "Philippines",
  TH: "Thailand",
  TN: "Tunisia",
  TR: "Turkey",
};

export function countryLabel(code) {
  if (!code) return "Unknown";
  const name = COUNTRY_NAMES[code.toUpperCase()];
  return name ? `${name} (${code})` : code;
}

export default COUNTRY_NAMES;
